### ISSUE TITLE
[Feature Request] Apple calendar?

### ISSUE THREAD

**Issue by k4mr4n** [AnandChowdhary/calendar-link#69]
Hi
great library but can you add support for apple calendar, please?

**Comment by k4mr4n** [comment]
I already created a PR for it but I cannot push it, I'm getting 403 error
can you give access, please?

**Comment by AnandChowdhary** [comment]
Hi @k4mr4n, thanks for opening this issue and adding support for Apple!

You're probably getting an HTTP `403` because you're trying to push commits to this repository directly. What you should be doing is creating a fork of this repo (by clicking on the "Fork" button on the top right) and pushing your commits to your fork. Then, you can open a pull request easily.

More information: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork.

**Comment by k4mr4n** [comment]
thanks @AnandChowdhary!
can you please do a quick release after both PRs got merged, thanks?

**Comment by AnandChowdhary** [comment]
@all-contributors Please add @k4mr4n for code
